### ISSUE TITLE
Server bug thing

### ISSUE THREAD

**Issue by RitzDx** [RealMCoded/LunarRec#12]
**Describe the bug**
When i start a build of 2017 with the lunarrec server, it says some banned related info then fails to connect to rec net.

**To Reproduce**
1.Start LunarRec
2.Open RecRoom
3.Recieve Info after this step
{ banned: false, reason: '', expires: 0 }
{ isBanned: false, data: {} }
4.Failed To Connect to rec net error

**Expected behavior**
For it to work, this part is unclear to my dumbahh brain

**Screenshots**
N/A

**System Information:**
 - Server OS: Windows 10
 - LunarRec Version: 0.1.0
 - LunarRec Commit: I dont know how to get a commit
 - Rec Room Version: October 17th 2017

**Additional context**
N/A

**Comment by nito9999** [comment]
same... but dev is inactive

**Comment by RealMCoded** [comment]
> When i start a build of 2017 with the lunarrec server, it says some banned related info then fails to connect to rec net.

Aware of this! haven't had time to fix due to other projects. No temporary solutions yet but I will try to patch it when i get the chance to ^^

**Comment by RealMCoded** [comment]
@RitzDx need some additional info from you real quick. Can you give me a full log of what happens when you get a connection? up to when it doesn't work?

**Comment by RitzDx** [comment]
@RealMCoded  I'm gonna try, i was using a openrec build, the issue was probably that i was using localhost, but i dont have a domain, and the http ip thing also doesnt work(Unless you can provide me a way on how to do it), trying to change the server url is gonna be hard, considering i dont know which dll/file it is located in

**Comment by RealMCoded** [comment]
>  i was using a openrec build

Ah! That's your problem. The websocket (WS) is hosted on the same port as the server (2017). where the OpenRec builds look for the port 20161. You would need to modify the build to work with the 2017.

I can do the modification for you. What version of 2017 are you using?

**Comment by RitzDx** [comment]
@RealMCoded 
 I was using September 15th 2017, if that is ok with you

**Comment by RitzDx** [comment]
if you was talking about what build i used that made that error, it was the openrec october 19th 2017 build

**Comment by RitzDx** [comment]
On second thought, I could do the server modification myself, i already patched the Photon realtime server and voice server using bepinex on a 2018 version, do you perchance know where the server url is stored?
