### ISSUE TITLE
Failed to load Rec Room player profiles

### ISSUE THREAD

**Issue by nito9999** [RealMCoded/LunarRec#9]
**Describe the bug**
Failed to load Rec Room player profiles on 2018 2017 and 2016

**To Reproduce**
1. Open LunarRec
2. Open Rec Room
3. "Failed to load Rec Room player profiles" error.

**Expected behavior**
To work

**System Information:**
 - Server OS: Windows 10
 - LunarRec Version: 0.1.0
 - LunarRec Commit: 0e2df02
 - Rec Room Version: 20180525_EA

**Comment by RealMCoded** [comment]
No endpoints for 2018 account loading exist yet, but they might exist in a future patch.

**Comment by nito9999** [comment]
it also happens in 2016 and 2017
